name: project-automation
on:
  issues:
    types: [opened, closed, reopened, labeled, unlabeled]
  pull_request_target:
    types: [opened, closed, reopened, converted_to_draft, ready_for_review, labeled, unlabeled]

permissions:
  contents: read

jobs:
  sync:
    uses: TechWatchProject/.github/.github/workflows/project_automation.yml@main
    secrets: inherit
